{"VDoc":{"$":{"PlatformName":"EESC336","PlatformSerialNumber":"520SLD511902","SoftwareBundleNumber":"21.4.0","SoftwareBuildNumber":"2.6.0.938 US","VATDatabaseName":"CH2V10GB.VAT","DateCreated":"09/17/2022  06:02AM","VehicleIdentificationNumber":"2GNAXUEV1K6267158","Odometer":"27194 mi","LicensePlateNumber":"ana","VehicleSystemReport":"Enabled"},"VDocSection":[{"$":{"Name":"COMPONENTDATA"},"DataItems":[{"$":{"componentName":"Scanner","attributeName":"ActionSelection"},"Item":[{"$":{"name":"MAKE","value":"Chevrolet"}},{"$":{"name":"YEAR","value":"2019"}},{"$":{"name":"MODEL","value":"Equinox (AWD)"}},{"$":{"name":"ENGINE","value":"1.5L L4 (LYX)"}},{"$":{"name":"SYSTEM","value":"CodeScan"}},{"$":{"name":"BEN","value":""}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"Item":[{"$":{"name":"TitleBar","value":"2019 Chevrolet Equinox (AWD) 1.5L L4 (LYX) "}},{"$":{"name":"InfoBar","value":"Code Scan Results"}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"CodeScanType":[{"$":{"name":"PostScan","value":"Post Scan"}}],"CodeScanSystems":[{"$":{"name":"Systems detected","value":"17"},"System":[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]}]}]}]}}





{"$":{"PlatformName":"EESC336","PlatformSerialNumber":"520SLD511902","SoftwareBundleNumber":"21.4.0","SoftwareBuildNumber":"2.6.0.938 US","VATDatabaseName":"CH2V10GB.VAT","DateCreated":"09/17/2022  06:02AM","VehicleIdentificationNumber":"2GNAXUEV1K6267158","Odometer":"27194 mi","LicensePlateNumber":"ana","VehicleSystemReport":"Enabled"},"VDocSection":[{"$":{"Name":"COMPONENTDATA"},"DataItems":[{"$":{"componentName":"Scanner","attributeName":"ActionSelection"},"Item":[{"$":{"name":"MAKE","value":"Chevrolet"}},{"$":{"name":"YEAR","value":"2019"}},{"$":{"name":"MODEL","value":"Equinox (AWD)"}},{"$":{"name":"ENGINE","value":"1.5L L4 (LYX)"}},{"$":{"name":"SYSTEM","value":"CodeScan"}},{"$":{"name":"BEN","value":""}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"Item":[{"$":{"name":"TitleBar","value":"2019 Chevrolet Equinox (AWD) 1.5L L4 (LYX) "}},{"$":{"name":"InfoBar","value":"Code Scan Results"}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"CodeScanType":[{"$":{"name":"PostScan","value":"Post Scan"}}],"CodeScanSystems":[{"$":{"name":"Systems detected","value":"17"},"System":[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]}]}]}]}


[{"$":{"Name":"COMPONENTDATA"},"DataItems":[{"$":{"componentName":"Scanner","attributeName":"ActionSelection"},"Item":[{"$":{"name":"MAKE","value":"Chevrolet"}},{"$":{"name":"YEAR","value":"2019"}},{"$":{"name":"MODEL","value":"Equinox (AWD)"}},{"$":{"name":"ENGINE","value":"1.5L L4 (LYX)"}},{"$":{"name":"SYSTEM","value":"CodeScan"}},{"$":{"name":"BEN","value":""}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"Item":[{"$":{"name":"TitleBar","value":"2019 Chevrolet Equinox (AWD) 1.5L L4 (LYX) "}},{"$":{"name":"InfoBar","value":"Code Scan Results"}}]},{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"CodeScanType":[{"$":{"name":"PostScan","value":"Post Scan"}}],"CodeScanSystems":[{"$":{"name":"Systems detected","value":"17"},"System":[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]}]}]}]



[{"componentName":"Scanner","attributeName":"CodeScan"},[{"$":{"name":"PostScan","value":"Post Scan"}}],[{"$":{"name":"Systems detected","value":"17"},"System":[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]}]]


{"$":{"componentName":"Scanner","attributeName":"CodeScan"},"CodeScanType":[{"$":{"name":"PostScan","value":"Post Scan"}}],"CodeScanSystems":[{"$":{"name":"Systems detected","value":"17"},"System":[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]}]}



[{"$":{"name":"Engine","type":"","value":"0"}},{"$":{"name":"Transmission","type":"","value":"0"}},{"$":{"name":"Antilock Brakes","type":"","value":"0"}},{"$":{"name":"Airbag","type":"","value":"0"}},{"$":{"name":"Body Control Module","type":"","value":"0"}},{"$":{"name":"HVAC","type":"","value":"0"}},{"$":{"name":"HVAC Controls","type":"","value":"0"}},{"$":{"name":"Instrument Panel Cluster","type":"","value":"0"}},{"$":{"name":"Keyless Entry","type":"","value":"0"}},{"$":{"name":"Liftgate Module","type":"","value":"0"}},{"$":{"name":"Parking Assist Module","type":"","value":"0"}},{"$":{"name":"Passenger Presence System","type":"","value":"0"}},{"$":{"name":"Radio","type":"","value":"0"}},{"$":{"name":"Serial Data Gateway Module","type":"","value":"0"}},{"$":{"name":"Side Object Detection Module","type":"Left","value":"0"}},{"$":{"name":"Telematics Communication Interface","type":"","value":"0"}},{"$":{"name":"Tire Pressure Monitor","type":"","value":"0"}},{"$":{"name":"OBDII","type":"Codes and monitors for this vehicle can be accessed using OBD-II/EOBD","value":"0"}},{"$":{"name":"OBDII Permanent Codes ($0A)","type":"","value":"0"}}]